services:
  web:
    build: .
    image: secdev-seed:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=secdev-seed
      - DEBUG=false  # Security: Disable debug in production
    # —— Security: Container hardening ————————————————————————————
    user: "appuser"  # Run as non-root user
    read_only: true  # Read-only root filesystem
    security_opt:
      - no-new-privileges:true  # Prevent privilege escalation
    tmpfs:  # Writable temporary directories
      - /tmp
      - /var/tmp
    # —— Healthcheck ——————————————————————————————————————————————
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s  # More reasonable interval
      timeout: 10s
      retries: 3
      start_period: 40s  # Give app time to start
    # —— Volumes for evidence and solutions ———————————————————————
    volumes:
      - ./solutions:/app/solutions:rw
      - ./EVIDENCE:/app/EVIDENCE:rw
      - ./logs:/app/logs:rw